// mapping['property_owner_updation'] = {
//     'AIN NUMBER',
//     'SA DATE OF\n LAST CHANGE',
//     'SA HOUSE NUMBER',
//     'SA FRACTION',
//     'SA DIRECTION',
//     'SA STREET NAME',
//     'SA UNIT TYPE',
//     'SA UNIT NUMBER',
//     'SA CITY',
//     'SA STATE',
//     'SA ZIP',
//     'SA COUNTY',
//     'SA REGION',
//     'SA NEIGHBORHOOD',
//     'SA NEIGHBORHOOD ID',
//     'PROPERTY \nRATING',
//     'NEIGHBORHOOD\n RATING',
//     'USE CODE',
//     'ZONING CODE',
//     'REAL ESTATE TYPE',
//     'PROP TYPE',
//     'PROP SUB-TYPE',
//     'SQUARE FEET',
//     'PROP UNITS',
//     'PROPERTY FLOORS',
//     'YEAR BUILT',
//     'LAST SALES DATE',
//     'LAST SALES PRICE',
//     'PROPERTY \nMANAGER',
//     'OWNERSHIP ENTITY',
//     'POTENTIAL OWNER',
//     'MA DATE OF \nLAST CHANGE',
//     'MA HOUSE NUMBER',
//     'MA FRACTION',
//     'MA DIRECTION',
//     'MA STREET NAME',
//     'UNIT TYPE',
//     'MA UNIT',
//     'MA CITY',
//     'MA STATE',
//     'MA ZIP',
//     'MA COUNTRY'
// };

module.exports = {
	
};